name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  camera: ^0.11.2
  http: ^1.5.0
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  mobile_scanner: ^6.0.11
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  go_router: ^16.1.0
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  tflite_flutter: ^0.11.0
  google_mlkit_commons: ^0.11.0
  google_ml_kit: ^0.20.0
  socket_io_client: ^2.0.3
  local_auth: ^2.1.0
  crypto: ^3.0.2
  file_picker: ^8.1.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # model files removed; no models packaged
